services:
  - type: web
    name: sales-app-backend
    env: node
    buildCommand: cd backend && npm install && npm run build && ls -la dist/
    startCommand: cd backend && npm run prod
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: sales-app-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://sales-app-backend.onrender.com
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        headers:
          Cache-Control: no-cache, no-store, must-revalidate
          Pragma: no-cache
          Expires: 0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0"
    autoDeploy: true 